---
- name: Create user for capistrano
  user:
    name: deploy
    comment: Capistrano Deployer
- name: Set authorized key to current user key
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: Build dependencies installed
  apt:
    pkg: ["build-essential", "postgresql-client", "libpq-dev", "libicu-dev", "libsqlite3-dev"]
    state: latest
- name: Deploy dependencies installed
  apt:
    pkg: ["git", "git-lfs"]
    state: latest
- name: Git lfs configured
  shell: git lfs install --system
- name: Create deployment dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
  with_items:
    - /var/www/ftc_results
    - /var/www/ftc_results/shared
    - /var/www/ftc_results/shared/log
- name: Grant deploy access
  template:
    src: 01-deploy.j2
    dest: /etc/sudoers.d/01-deploy
- name: Copy the logrotate files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'logrotate.conf.j2', dest: '/etc/logrotate.d/ftc_results' }