---
- name: Create user for capistrano
  user:
    name: deploy
    comment: Capistrano Deployer
- name: Set authorized key to current user key
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: Brightbox ruby availible
  apt_repository:
    repo: ppa:brightbox/ruby-ng
- name: Latest version of Ruby is installed
  apt:
    pkg: ["ruby2.6", "ruby2.6-dev"]
    state: latest
- name: Build dependencies installed
  apt:
    pkg: ["build-essential", "postgresql-client", "libpq-dev", "libicu-dev", "libsqlite3-dev"]
    state: latest
- name: Bundler installed
  gem:
    name: bundler
    user_install: no
    state: latest
- name: Create deployment dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
  with_items:
    - /var/www/ftc_results
    - /var/www/ftc_results/shared
    - /var/www/ftc_results/shared/log
- name: Grant deploy access
  template:
    src: 01-deploy.j2
    dest: /etc/sudoers.d/01-deploy
- name: Copy the logrotate files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'logrotate.conf.j2', dest: '/etc/logrotate.d/ftc_results' }