# This can be copied into your local ~/.aws/config file for easy use of `AWS_PROFILE` etc

[sso-session maths22]
sso_start_url           = https://maths22.awsapps.com/start/
sso_region              = us-west-2
sso_registration_scopes = sso:account:access

[profile maths22]
sso_session    = maths22
sso_account_id = 902151335766
sso_role_name  = Admin
region         = us-west-2

[profile maths22-fir]
sso_session    = maths22
sso_account_id = 119630856374
sso_role_name  = Admin
region         = us-west-2