---
- name: Instructure ruby availible
  apt_repository:
    repo: ppa:instructure/ruby
- name: Latest version of Ruby and some version of node is installed
  apt:
    update_cache: true
    pkg: ["ruby3.2", "ruby3.2-dev", "libjemalloc-dev", "nodejs"]
    state: latest
- name: Set LD_PRELOAD
  lineinfile:
    path: /etc/environment
    regexp: '^LD_PRELOAD'
    line: 'LD_PRELOAD=/usr/lib/{{ ansible_architecture }}-linux-gnu/libjemalloc.so'
- name: Bundler installed
  gem:
    name: bundler
    user_install: no
    state: latest
#- name: Monitoring installed
#  shell: "curl https://agent.servermonitoring.me/agent/installer | bash -s {{ monitoring_key }}"
#  args:
#    creates: /etc/init.d/cloudstats-agent