---
- name: Brightbox ruby availible
  apt_repository:
    repo: ppa:brightbox/ruby-ng
- name: Latest version of Ruby is installed
  apt:
    pkg: ["ruby2.6", "ruby2.6-dev", "libjemalloc-dev"]
    state: latest
- name: Set LD_PRELOAD
  lineinfile:
    path: /etc/environment
    regexp: '^LD_PRELOAD'
    line: 'LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1'
- name: Bundler installed
  gem:
    name: bundler
    user_install: no
    state: latest
- name: Monitoring installed
  shell: "curl https://agent.servermonitoring.me/agent/installer | bash -s {{ monitoring_key }}"
  args:
    creates: /etc/init.d/cloudstats-agent