---
- name: Copy the jobs files
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'inst_jobs.service.j2', dest: '/etc/systemd/system/inst_jobs.service' }
  register: update_jobs
- name: restart inst_jobs
  systemd:
    daemon_reload: true
    name: inst_jobs
    enabled: yes
    state: restarted
  when: update_jobs.changed